name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "kvupward"
        secrets: 'kvusername, kvpassword'
      id: kvupward
    
    - uses: azure/docker-login@v1
      with:
        login-server: azureupward.azurecr.io
        username: ${{ steps.myGetSecretAction.outputs.kvusername }}
        password: ${{ steps.myGetSecretAction.outputs.kvpassword }}

    - run: |
        docker build . -t azureupward.azurecr.io/upward2020devops:${{ github.sha }}
        docker tag azureupward.azurecr.io/upward2020devops:${{ github.sha }} azureupward.azurecr.io/upward2020devops:latest
        docker push azureupward.azurecr.io/upward2020devops:${{ github.sha }}
        docker push azureupward.azurecr.io/upward2020devops:latest
   
    - uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/demoserievideo1/AzureUpward'
        azure-pipeline-name: 'upward-docker' # name of the Azure pipeline to be triggered
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
